name: Validate Code

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Python Version
        id: python-version
        run: |
          version=$(grep requires-python pyproject.toml | grep -Eo [0-9]+.[0-9]+)
          if [ -z $version ]; then
            echo "Failed to parse version from pyproject.toml"
            exit 1
          fi
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Set up Python ${{ steps.python-version.outputs.version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.python-version.outputs.version }}

      - name: Install Validate Dependencies
        run: |
          pip install -r requirements_dev.txt
          sudo apt-get install libtre-dev libturbojpeg0-dev -y
          make build-all

      - name: Validate Config.ini Schema
        run: python ./config_schema_validator.py

      - name: Validate
        run: |
          chmod +x ./validate.sh
          ./validate.sh

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

        # xvfb enables tkinter in these tests
      - name: Unit Tests
        run: |
          export DISPLAY=:99
          Xvfb :99 &
          make test
