name: Validate Code

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Validate Dependencies
        run: |
          pip install -r requirements_dev.txt

      - name: Validate
        run: |
          chmod +x ./validate.sh
          ./validate.sh
        shell: bash

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get install -y libturbojpeg

          curl -O -L --output /usr/share/fonts https://ultralytics.com/assets/Arial.ttf

        # xvfb enables tkinter in these tests
      - name: Unit Tests
        run: |
          export DISPLAY=:99
          Xvfb :99 &
          chmod +x ./run_tests.sh
          ./run_tests.sh
        shell: bash
